apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vote.serviceName }}
  labels:
    app: {{ .Values.vote.name }}
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.vote.serviceName }}
    port: {{ .Values.vote.port }}
    targetPort: {{ .Values.vote.targetPort }}
  selector:
    app: {{ .Values.vote.name }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vote.name }}
  labels:
    app: {{ .Values.vote.name }}
spec:
  replicas: {{ .Values.vote.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.vote.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.vote.name }}
    spec:
      containers:
      - image: {{ .Values.githubRegistry }}/{{ .Values.vote.image }}:{{ .Values.vote.tag }}
        name: {{ .Values.vote.name }}
        ports:
        - containerPort: {{ .Values.vote.targetPort }}
          name: {{ .Values.vote.serviceName }}